from SPearC import *
import pandas as pd
from Graphing import *

Room_1 = pd.read_csv('.\\Data\\Room-1.csv',index_col=0)
R1DAT = Room_1['Discharge Air Temperature'].tolist()
R1ZT = Room_1['Zone Temperature'].tolist()
R1A = Room_1['Airflow'].tolist()
R1DZ_P = tlcc_pearson(R1DAT,R1ZT)
R1DZ_S = tlcc_spearman(R1DAT,R1ZT)
R1DA_P = tlcc_pearson(R1DAT,R1A)
R1DA_S = tlcc_spearman(R1DAT,R1A)
R1ZA_P = tlcc_pearson(R1ZT,R1A)
R1ZA_S = tlcc_spearman(R1ZT,R1A)

Room_2 = pd.read_csv('.\\Data\\Room-2.csv',index_col=0)
R2DAT = Room_2['Discharge Air Temperature'].tolist()
R2ZT = Room_2['Zone Temperature'].tolist()
R2A = Room_2['Airflow'].tolist()
R2DZ_P = tlcc_pearson(R2DAT,R2ZT)
R2DZ_S = tlcc_spearman(R2DAT,R2ZT)
R2DA_P = tlcc_pearson(R2DAT,R2A)
R2DA_S = tlcc_spearman(R2DAT,R2A)
R2ZA_P = tlcc_pearson(R2ZT,R2A)
R2ZA_S = tlcc_spearman(R2ZT,R2A)


Room_3 = pd.read_csv('.\\Data\\Room-3.csv',index_col=0)
R3DAT = Room_3['Discharge Air Temperature'].tolist()
R3ZT = Room_3['Zone Temperature'].tolist()
R3A = Room_3['Airflow'].tolist()
R3DZ_P = tlcc_pearson(R3DAT,R3ZT)
R3DZ_S = tlcc_spearman(R3DAT,R3ZT)
R3DA_P = tlcc_pearson(R3DAT,R3A)
R3DA_S = tlcc_spearman(R3DAT,R3A)
R3ZA_P = tlcc_pearson(R3ZT,R3A)
R3ZA_S = tlcc_spearman(R3ZT,R3A)

Room_4 = pd.read_csv('.\\Data\\Room-4.csv',index_col=0)
R4DAT = Room_4['Discharge Air Temperature'].tolist()
R4ZT = Room_4['Zone Temperature'].tolist()
R4A = Room_4['Airflow'].tolist()
R4DZ_P = tlcc_pearson(R4DAT,R4ZT)
R4DZ_S = tlcc_spearman(R4DAT,R4ZT)
R4DA_P = tlcc_pearson(R4DAT,R4A)
R4DA_S = tlcc_spearman(R4DAT,R4A)
R4ZA_P = tlcc_pearson(R4ZT,R4A)
R4ZA_S = tlcc_spearman(R4ZT,R4A)


Room_5 = pd.read_csv('.\\Data\\Room-5.csv',index_col=0)
R5DAT = Room_5['Discharge Air Temperature'].tolist()
R5ZT = Room_5['Zone Temperature'].tolist()
R5A = Room_5['Airflow'].tolist()
R5DZ_P = tlcc_pearson(R5DAT,R5ZT)
R5DZ_S = tlcc_spearman(R5DAT,R5ZT)
R5DA_P = tlcc_pearson(R5DAT,R5A)
R5DA_S = tlcc_spearman(R5DAT,R5A)
R5ZA_P = tlcc_pearson(R5ZT,R5A)
R5ZA_S = tlcc_spearman(R5ZT,R5A)

Room_6 = pd.read_csv('.\\Data\\Room-6.csv',index_col=0)
R6DAT = Room_6['Discharge Air Temperature'].tolist()
R6ZT = Room_6['Zone Temperature'].tolist()
R6A = Room_6['Airflow'].tolist()
R6DZ_P = tlcc_pearson(R6DAT,R6ZT)
R6DZ_S = tlcc_spearman(R6DAT,R6ZT)
R6DA_P = tlcc_pearson(R6DAT,R6A)
R6DA_S = tlcc_spearman(R6DAT,R6A)
R6ZA_P = tlcc_pearson(R6ZT,R6A)
R6ZA_S = tlcc_spearman(R6ZT,R6A)

Room_7 = pd.read_csv('.\\Data\\Room-7.csv',index_col=0)
R7DAT = Room_7['Discharge Air Temperature'].tolist()
R7ZT = Room_7['Zone Temperature'].tolist()
R7A = Room_7['Airflow'].tolist()
R7DZ_P = tlcc_pearson(R7DAT,R7ZT)
R7DZ_S = tlcc_spearman(R7DAT,R7ZT)
R7DA_P = tlcc_pearson(R7DAT,R7A)
R7DA_S = tlcc_spearman(R7DAT,R7A)
R7ZA_P = tlcc_pearson(R7ZT,R7A)
R7ZA_S = tlcc_spearman(R7ZT,R7A)

Room_8 = pd.read_csv('.\\Data\\Room-8.csv',index_col=0)
R8DAT = Room_8['Discharge Air Temperature'].tolist()
R8A = Room_8['Airflow'].tolist()
R8DA_P = tlcc_pearson(R8DAT,R8A)
R8DA_S = tlcc_spearman(R8DAT,R8A)


Room_9 = pd.read_csv('.\\Data\\Room-9.csv',index_col=0)
R9DAT = Room_9['Discharge Air Temperature'].tolist()
R9A = Room_9['Airflow'].tolist()
R9DA_P = tlcc_pearson(R9DAT,R9A)
R9DA_S = tlcc_spearman(R9DAT,R9A)

Room_10 = pd.read_csv('.\\Data\\Room-10.csv',index_col=0)
R10DAT = Room_10['Discharge Air Temperature'].tolist()
R10ZT = Room_10['Zone Temperature'].tolist()
R10A = Room_10['Airflow'].tolist()
R10DZ_P = tlcc_pearson(R10DAT,R10ZT)
R10DZ_S = tlcc_spearman(R10DAT,R10ZT)
R10DA_P = tlcc_pearson(R10DAT,R10A)
R10DA_S = tlcc_spearman(R10DAT,R10A)
R10ZA_P = tlcc_pearson(R10ZT,R10A)
R10ZA_S = tlcc_spearman(R10ZT,R10A)
