from SPearC import *
from FTT import *
from Graphing import *
import pandas as pd

Room_1 = pd.read_csv('.\\Data\\Room-1.csv',index_col=0)
R1DAT = Room_1['Discharge Air Temperature'].tolist()
R1ZT = Room_1['Zone Temperature'].tolist()
R1A = Room_1['Airflow'].tolist()
FFT_with_graphes(R1DAT)
FFT_with_graphes(R1ZT)
FFT_with_graphes(R1A)

Room_2 = pd.read_csv('.\\Data\\Room-2.csv',index_col=0)
R2DAT = Room_2['Discharge Air Temperature'].tolist()
R2ZT = Room_2['Zone Temperature'].tolist()
R2A = Room_2['Airflow'].tolist()
FFT_with_graphes(R2DAT)
FFT_with_graphes(R2ZT)
FFT_with_graphes(R2A)

Room_3 = pd.read_csv('.\\Data\\Room-3.csv',index_col=0)
R3DAT = Room_3['Discharge Air Temperature'].tolist()
R3ZT = Room_3['Zone Temperature'].tolist()
R3A = Room_3['Airflow'].tolist()
FFT_with_graphes(R3DAT)
FFT_with_graphes(R3ZT)
FFT_with_graphes(R3A)

Room_4 = pd.read_csv('.\\Data\\Room-4.csv',index_col=0)
R4DAT = Room_4['Discharge Air Temperature'].tolist()
R4ZT = Room_4['Zone Temperature'].tolist()
R4A = Room_4['Airflow'].tolist()
FFT_with_graphes(R4DAT)
FFT_with_graphes(R4ZT)
FFT_with_graphes(R4A)

Room_5 = pd.read_csv('.\\Data\\Room-5.csv',index_col=0)
R5DAT = Room_5['Discharge Air Temperature'].tolist()
R5ZT = Room_5['Zone Temperature'].tolist()
R5A = Room_5['Airflow'].tolist()
FFT_with_graphes(R5DAT)
FFT_with_graphes(R5ZT)
FFT_with_graphes(R5A)

Room_6 = pd.read_csv('.\\Data\\Room-6.csv',index_col=0)
R6DAT = Room_6['Discharge Air Temperature'].tolist()
R6ZT = Room_6['Zone Temperature'].tolist()
R6A = Room_6['Airflow'].tolist()
FFT_with_graphes(R6DAT)
FFT_with_graphes(R6ZT)
FFT_with_graphes(R6A)

Room_7 = pd.read_csv('.\\Data\\Room-7.csv',index_col=0)
R7DAT = Room_7['Discharge Air Temperature'].tolist()
R7ZT = Room_7['Zone Temperature'].tolist()
R7A = Room_7['Airflow'].tolist()
FFT_with_graphes(R7DAT)
FFT_with_graphes(R7ZT)
FFT_with_graphes(R7A)

Room_8 = pd.read_csv('.\\Data\\Room-8.csv',index_col=0)
R8DAT = Room_8['Discharge Air Temperature'].tolist()
R8ZT = Room_8['Zone Temperature'].tolist()
R8A = Room_8['Airflow'].tolist()
FFT_with_graphes(R8DAT)
FFT_with_graphes(R8ZT)
FFT_with_graphes(R8A)

Room_9 = pd.read_csv('.\\Data\\Room-9.csv',index_col=0)
R9DAT = Room_9['Discharge Air Temperature'].tolist()
R9ZT = Room_9['Zone Temperature'].tolist()
R9A = Room_9['Airflow'].tolist()
FFT_with_graphes(R9DAT)
FFT_with_graphes(R9ZT)
FFT_with_graphes(R9A)

Room_10 = pd.read_csv('.\\Data\\Room-10.csv',index_col=0)
R10DAT = Room_10['Discharge Air Temperature'].tolist()
R10ZT = Room_10['Zone Temperature'].tolist()
R10A = Room_10['Airflow'].tolist()
FFT_with_graphes(R10DAT)
FFT_with_graphes(R10ZT)
FFT_with_graphes(R10A)
